name: run bdsim regression

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:

  regression:
    name: run regression
    runs-on: ubuntu-latest
    container: bdsim/${{ matrix.dockerimage }}:develop

    strategy:
      fail-fast: false
      matrix:
        dockerimage: [ alma9-g4.10.7-bdsim, alma9-g4.11.0-bdsim,
                       alma9-g4.11.1-bdsim, alma9-g4.11.2-bdsim,
                       alma9-g4.11.3-bdsim, alma9-g4.11.4-bdsim]

    steps:
      - name: Checkout regression
        uses: actions/checkout@v4
        id: checkout

      - name: Run regression tests
        run: |
          yum install which -y 
          source /root/.bashrc
          source /bdsim/root/bin/thisroot.sh
          source /bdsim/venv-bdsim/bin/activate
          # update pybdsim for development
          /bdsim/venv-bdsim/bin/pip uninstall pybdsim -y
          /bdsim/venv-bdsim/bin/pip install git+https://github.com/bdsim-collaboration/pybdsim.git@develop
          # install dependencies
          /bdsim/venv-bdsim/bin/pip install pytest
          /bdsim/venv-bdsim/bin/pip install xsuite
          /bdsim/venv-bdsim/bin/pip install ocelot-desy
          /bdsim/venv-bdsim/bin/pip install rf-track
          /bdsim/venv-bdsim/bin/pip install rpyc
          export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python/
          export LD_PRELOAD="libG4processes.so:libstdc++.so.6:libG4geometry.so"
          pytest -v