name: run bdsim regression

on:
  release:
    types: [published]
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  regression:
    name: run regression
    runs-on: ubuntu-latest
    container: bdsim/${{ matrix.dockerimage }}:develop

    strategy:
      fail-fast: false
      matrix:
        dockerimage: [ alma10-g4.10.7-bdsim, alma10-g4.11.0-bdsim,
                       alma10-g4.11.1-bdsim, alma10-g4.11.2-bdsim,
                       alma10-g4.11.3-bdsim, alma10-g4.11.4-bdsim]

    steps:
      - name: Checkout regression
        uses: actions/checkout@v4
        id: checkout

      - name: Echo number of cores
        shell: bash
        run: echo "Number of cores ${{ steps.cpu-cores.outputs.count }}"

      - name: Run regression tests
        shell: bash
        run: |
          # debug
          ls -trl 
          pwd
          
          # install which
          yum install which -y 
          
          # configure BDSIM stack
          source /bdsim/setup.sh
          
          # update pybdsim for development (dev for testing and pytest)
          /bdsim/venv-bdsim/bin/pip uninstall pybdsim -y
          /bdsim/venv-bdsim/bin/pip install "pybdsim[dev] @ git+https://github.com/bdsim-collaboration/pybdsim.git@develop"
          
          # install dependencies
          /bdsim/venv-bdsim/bin/pip install pytest 
          /bdsim/venv-bdsim/bin/pip install xsuite
          /bdsim/venv-bdsim/bin/pip install ocelot-desy
          /bdsim/venv-bdsim/bin/pip install rf-track
          /bdsim/venv-bdsim/bin/pip install rpyc
          /bdsim/venv-bdsim/bin/pip install pytest-xdist
          /bdsim/venv-bdsim/bin/pip install dominate
          export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python/
          
          # alma10
          export GLIBC_TUNABLES=glibc.rtld.optional_static_tls=2097152
          pytest -v -runxfail -n 0
          
          # gatherup regression output 
          /bdsim/venv-bdsim/bin/python regression_data.py copy --file=./regression_data.dat --destination=${{ matrix.dockerimage }}
          tar zcf ./${{ matrix.dockerimage }}.tgz ${{ matrix.dockerimage }}
          
          echo ${{ github.event_name }}

      - name: Create regression release
        if : github.event_name == 'release'
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          allowUpdates: true

      - name: Upload regression output
        if: github.event_name  == 'release'
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ matrix.dockerimage }}.tgz
          asset_name: ${{ matrix.dockerimage }}.tgz
          asset_content_type: application/gzip


  after-matrix:
    name: Regression webpage
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: regression
    steps:
      - name: Checkout regression
        uses: actions/checkout@v4
        id: checkout

      - name: Echo number of cores
        shell: bash
        run: echo "Number of cores ${{ steps.cpu-cores.outputs.count }}"